CREATE DATABASE buy;

USE buy;

-- CUSTOMER table 
CREATE TABLE CUSTOMER(
  ID INT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL
);

INSERT INTO CUSTOMER VALUES (1,'NILOY');
INSERT INTO CUSTOMER VALUES (2,'ASMA');

-- PRODUCTS table
CREATE TABLE PRODUCTS(
  PRODUCT_ID INT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  PRICE INT CHECK (PRICE > 0)
);

INSERT INTO PRODUCTS VALUES (1,'Laptop',80000);
INSERT INTO PRODUCTS VALUES (2,'Mouse',500);
INSERT INTO PRODUCTS VALUES (3,'Keyboard',1500);

-- Safe drop
DROP TABLE IF EXISTS ORDERS;

-- ORDERS table
CREATE TABLE ORDERS(
  ORDER_ID INT PRIMARY KEY,
  CUSTOMER_ID INT,
  PRODUCT_ID INT,
  AMOUNT INT,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

INSERT INTO ORDERS VALUES (101,1,1,80000);
INSERT INTO ORDERS VALUES (102,2,2,500);
INSERT INTO ORDERS VALUES (103,1,3,1500);

--  Basic JOIN
SELECT CUSTOMER.NAME, PRODUCTS.NAME AS PRODUCT, ORDERS.AMOUNT
FROM ORDERS
INNER JOIN CUSTOMER ON CUSTOMER.ID = ORDERS.CUSTOMER_ID
INNER JOIN PRODUCTS ON PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT_ID;

-- Advanced Query: Total spending per customer
SELECT CUSTOMER.NAME, SUM(ORDERS.AMOUNT) AS TOTAL_SPENT
FROM ORDERS
INNER JOIN CUSTOMER ON CUSTOMER.ID = ORDERS.CUSTOMER_ID
GROUP BY CUSTOMER.ID, CUSTOMER.NAME
ORDER BY TOTAL_SPENT DESC;

--  Advanced Query: Most sold product
SELECT PRODUCTS.NAME, COUNT(*) AS TOTAL_SOLD
FROM ORDERS
INNER JOIN PRODUCTS ON PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT_ID
GROUP BY PRODUCTS.PRODUCT_ID, PRODUCTS.NAME
ORDER BY TOTAL_SOLD DESC;
