CREATE DATABASE buy;

USE buy;

-- CUSTOMER table 
CREATE TABLE CUSTOMER(
  ID INT PRIMARY KEY,
  NAME VARCHAR(50)
);

INSERT INTO CUSTOMER VALUES (1,'NILOY');
INSERT INTO CUSTOMER VALUES (2,'ASMA');

-- PRODUCTS table
CREATE TABLE PRODUCTS(
  PRODUCT_ID INT PRIMARY KEY,
  NAME VARCHAR(50),
  PRICE INT
);

INSERT INTO PRODUCTS VALUES (1,'Laptop',80000);
INSERT INTO PRODUCTS VALUES (2,'Mouse',500);
INSERT INTO PRODUCTS VALUES (3,'Keyboard',1500);

-- Safe drop
DROP TABLE IF EXISTS ORDERS;

-- ORDERS table
CREATE TABLE ORDERS(
  ORDER_ID INT PRIMARY KEY,
  CUSTOMER_ID INT,
  PRODUCT_ID INT,
  AMOUNT INT,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

INSERT INTO ORDERS VALUES (101,1,1,80000);
INSERT INTO ORDERS VALUES (102,2,2,500);
INSERT INTO ORDERS VALUES (103,1,3,1500);

-- FINAL JOIN
SELECT CUSTOMER.NAME, PRODUCTS.NAME, ORDERS.AMOUNT
FROM ORDERS
INNER JOIN CUSTOMER ON CUSTOMER.ID = ORDERS.CUSTOMER_ID
INNER JOIN PRODUCTS ON PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT_ID;
